 E2e-Regression-execution:
    stage: test
    image: maven:3.8-openjdk-8
    allow_failure: true
    script:

#    - mvn clean
#    - mvn test
     - /etc/apache-maven-3.8.4/bin/mvn clean
     - /etc/apache-maven-3.8.4/bin/mvn test -Dcucumber.filter.tags="@call18" -Dbackend="3.17.7.15" -Dkeycloak="3.17.40.22" -Dcucumber.options="--plugin html:target/cucumber.html"
    artifacts:
      name: "E2e_Report"
      paths:
      - target/cucumber.html
      expire_in: 1 day

