stages:
  - test
  - report
test-execution: 
  stage: test
  tags:
    - aws-gitlab-runner
  image: maven:3.8-openjdk-8
  script:
#    - mvn clean
#    - mvn test
    - (/etc/apache-maven-3.8.4/bin/mvn clean)
    - (/etc/apache-maven-3.8.4/bin/mvn clean install -U -Dcucumber.filter.tags="@envUS" -Dbackend="18.189.91.1" -Dkeycloak="18.189.91.1" -Dplatform="18.189.91.1" -Dasrengine="18.190.37.12:2800" -Dcucumber.options="--plugin html:target/cucumber.html")

  stage: report
  artifacts:
    name: "E2e_Report"
    paths:
    - target/cucumber.html
    expire_in: 1 day
