stages:
  - test-setup
  - test-smoke
  - test-reports
.test-setup: 
  stage: test-setup
  tags:
    - aws-gitlab-runner
  image: maven:3.8-openjdk-8
  script:
#    - mvn clean
#    - mvn test
    - (/etc/apache-maven-3.8.4/bin/mvn clean)
    - (/etc/apache-maven-3.8.4/bin/mvn clean install -U -Dcucumber.filter.tags="@envUS" -Dbackend="3.13.70.184" -Dkeycloak="3.13.70.184" -Dplatform="3.13.70.184" -Dasrengine="18.119.154.56:2800")


test-smoke: 
  stage: test-smoke
  tags:
    - aws-gitlab-runner
  image: maven:3.8-openjdk-8
  script:

    - (/etc/apache-maven-3.8.4/bin/mvn clean install -U -Dcucumber.filter.tags="@US" -Dbackend="3.13.70.184" -Dkeycloak="3.13.70.184" -Dplatform="3.13.70.184" -Dasrengine="18.119.154.56:2800" -Dcucumber.options="--plugin html:target/cucumber.html")
    - pwd
  artifacts:
    name: "e2e_smoke_report"
    paths:
    - target/cucumber.html
    expire_in: 2 day
