stages:
  - build
  - test

build-code-job:
  stage: build
  tags:
    - auto-runner
  script:
    - echo "To be integrated with dev branch"

test-job:
  stage: test
  tags:
    - auto-runner
  script:
    - mvn clean
    - mvn test -Dcucumber.filter.tags="@call18" -Dbackend="3.17.7.15" -Dkeycloak="3.17.40.22"
