stages:
  - test-setup
  - test-smoke
  - test-reports
  - deploy-artifacts

test-setup: 
  stage: test-setup
  tags:
    - aws-gitlab-runner
  image: maven:3.8-openjdk-8
  script:
#    - mvn clean
#    - mvn test
    - (/etc/apache-maven-3.8.4/bin/mvn clean)
    - (/etc/apache-maven-3.8.4/bin/mvn clean install -U -Dcucumber.filter.tags="@envUS" -Dbackend="3.23.77.109" -Dkeycloak="18.119.39.12" -Dplatform="3.20.46.164" -Dasrengine="3.23.77.109:2800")


test-smoke: 
  stage: test-smoke
  tags:
    - aws-gitlab-runner
  image: maven:3.8-openjdk-8
  script:
    - (/etc/apache-maven-3.8.4/bin/mvn clean install -U -Dcucumber.filter.tags="@US" -Dbackend="3.23.77.109" -Dkeycloak="18.119.39.12" -Dplatform="3.20.46.164" -Dasrengine="3.23.77.109:2800" -Dcucumber.options="--plugin html:target/cucumber.html")
    
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - target/cucumber.html
    expire_in: 5 day

deploy-artifacts:
  stage: deploy-artifacts
  script:
    - curl -ueliyaspraveen@uniphore.com:AP8CvHAdgvxyawWP5ETJd8SVvdz -T target/cucumber.html "https://qabuilds.jfrog.io/artifactory/default-generic-local/cucumber.html"



