E2e-Regression:
  stage: test
  image: maven:3.8-openjdk-8
  script:
#    - mvn clean
#    - mvn test
    - (sh  /etc/apache-maven-3.8.4/bin/mvn clean install)
    - (sh  /etc/apache-maven-3.8.4/bin/mvn test -Dcucumber.filter.tags="@call18" -Dbackend="3.17.7.15" -Dkeycloak="3.17.40.22" -Dcucumber.options="--plugin html:target/cucumber.html")
