stages:
  - test
  - report
test-execution:  
  stage: test
  tags:
    - aws-gitlab-runner
  image: maven:3.8-openjdk-8
  script:
#    - mvn clean
#    - mvn test
    - (/etc/apache-maven-3.8.4/bin/mvn clean)
    - (/etc/apache-maven-3.8.4/bin/mvn test -Dcucumber.filter.tags="@env" -Dbackend="3.140.55.216" -Dkeycloak="3.140.55.216" -Dplatform=”3.140.55.216” -Dcucumber.options="--plugin html:target/cucumber.html")
#    - (/etc/apache-maven-3.8.4/bin/mvn test -Dcucumber.filter.tags="@smoke" -Dbackend="3.140.55.216" -Dkeycloak="3.140.55.216" -Dplatform=”3.140.55.216” -Dcucumber.options="--plugin html:target/cucumber.html")

# test-report:  
#   stage: report
  artifacts:
    name: "E2e_Report"
    paths:
    - target/cucumber.html
    expire_in: 5 day
