test-job:
  stage: test
  image: maven:3.8-openjdk-11
  script:
    - mvn clean
#    - mvn test
    - mvn test -Dcucumber.filter.tags="@call18" -Dbackend="3.17.7.15" -Dkeycloak="3.17.40.22" -Dcucumber.options="--plugin html:target/cucumber.html"
